"use client";

/**
 * ESignDocument Component — CCA-licensed digital signature for documents.
 *
 * Implements the India Stack eSign flow for digitally signing finalized
 * MoM documents with legally valid PKCS#7 signatures.
 *
 * Flow: Compute doc hash → Initiate eSign → Enter OTP → Apply signature
 *
 * In production, signatures are generated by CCA-licensed providers
 * (Protean eGov / NSDL) using short-term X.509 certificates.
 */

import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import {
  PenTool,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  FileKey,
  Shield,
  Clock,
} from "lucide-react";
import { cn } from "@/lib/utils";
import {
  initiateESignOTP,
  executeESign,
  type ESignResponse,
  type ESignStatus,
} from "@/lib/india-stack";

interface ESignDocumentProps {
  /** SHA-256 hash of the document to sign */
  documentHash: string;
  /** Name of the signer (from e-KYC or session) */
  signerName: string;
  /** Designation of the signer */
  signerDesignation?: string;
  /** Document name for display */
  documentName?: string;
  /** Called when signing completes */
  onSigned?: (signature: NonNullable<ESignResponse["signature"]>) => void;
  /** Additional CSS class */
  className?: string;
}

export function ESignDocument({
  documentHash,
  signerName,
  signerDesignation = "CECB Official",
  documentName = "Minutes of Meeting",
  onSigned,
  className,
}: ESignDocumentProps) {
  const [status, setStatus] = useState<ESignStatus>("pending");
  const [otp, setOtp] = useState("");
  const [transactionId, setTransactionId] = useState("");
  const [signature, setSignature] = useState<ESignResponse["signature"] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleInitiate = useCallback(async () => {
    setError(null);
    setLoading(true);
    try {
      const result = await initiateESignOTP(signerName, documentHash);
      if (result.success) {
        setTransactionId(result.transactionId);
        setStatus("otp_sent");
      } else {
        setError("Failed to initiate eSign. Please try again.");
      }
    } catch {
      setError("eSign service unavailable.");
    } finally {
      setLoading(false);
    }
  }, [signerName, documentHash]);

  const handleSign = useCallback(async () => {
    setError(null);
    setLoading(true);
    try {
      const result = await executeESign({
        documentHash,
        signerName,
        signerDesignation,
        purpose: `Digital signature for ${documentName}`,
        ekycTransactionId: transactionId,
        otp,
      });

      if (result.success && result.signature) {
        setSignature(result.signature);
        setStatus("signed");
        onSigned?.(result.signature);
      } else {
        setError(result.error?.message || "Signing failed.");
        setStatus("failed");
      }
    } catch {
      setError("Signing failed. Please try again.");
      setStatus("failed");
    } finally {
      setLoading(false);
    }
  }, [documentHash, signerName, signerDesignation, documentName, transactionId, otp, onSigned]);

  // Signed state — show signature details
  if (status === "signed" && signature) {
    return (
      <Card className={cn("border-green-200 dark:border-green-500/30", className)}>
        <CardHeader className="pb-3">
          <div className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-full bg-green-100 dark:bg-green-500/20 flex items-center justify-center">
              <CheckCircle2 className="h-5 w-5 text-green-600 dark:text-green-400" />
            </div>
            <div>
              <CardTitle className="text-lg text-green-700 dark:text-green-300">
                Digitally Signed
              </CardTitle>
              <CardDescription>PKCS#7 signature applied via CCA-licensed ESP</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div>
              <p className="text-muted-foreground text-xs">Signer</p>
              <p className="font-medium">{signerName}</p>
            </div>
            <div>
              <p className="text-muted-foreground text-xs">Certificate Serial</p>
              <p className="font-mono text-xs">{signature.certificateSerial}</p>
            </div>
            <div>
              <p className="text-muted-foreground text-xs">Issuer</p>
              <p className="text-xs">{signature.issuer}</p>
            </div>
            <div>
              <p className="text-muted-foreground text-xs">Signed At</p>
              <p className="text-xs">{new Date(signature.signedAt).toLocaleString()}</p>
            </div>
          </div>

          <div className="bg-muted/50 p-3 rounded-lg space-y-1">
            <p className="text-xs text-muted-foreground">Document Hash (SHA-256)</p>
            <p className="font-mono text-xs break-all">{signature.documentHash}</p>
          </div>

          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1 text-xs text-green-600 dark:text-green-400">
              <Shield className="h-3 w-3" />
              Legally valid under IT Act 2000, Sec. 3A
            </div>
            <div className="flex items-center gap-1 text-xs text-muted-foreground ml-auto">
              <Clock className="h-3 w-3" />
              Certificate valid until {new Date(signature.validTo).toLocaleTimeString()}
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={cn("border-border/50", className)}>
      <CardHeader className="pb-3">
        <div className="flex items-center gap-2">
          <PenTool className="h-5 w-5 text-primary" />
          <CardTitle className="text-lg">Digital Signature (eSign)</CardTitle>
        </div>
        <CardDescription>
          Apply CCA-licensed digital signature to {documentName}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Document info */}
        <div className="bg-muted/30 p-3 rounded-lg space-y-2">
          <div className="flex items-center gap-2 text-sm">
            <FileKey className="h-4 w-4 text-muted-foreground" />
            <span className="font-medium">{documentName}</span>
          </div>
          <div>
            <p className="text-xs text-muted-foreground">SHA-256 Hash</p>
            <p className="font-mono text-xs break-all">{documentHash}</p>
          </div>
          <div className="text-xs text-muted-foreground">
            Signer: {signerName} ({signerDesignation})
          </div>
        </div>

        {/* Initiate button */}
        {status === "pending" && (
          <Button onClick={handleInitiate} disabled={loading} className="w-full gap-2">
            {loading ? (
              <><Loader2 className="h-4 w-4 animate-spin" /> Initiating...</>
            ) : (
              <><PenTool className="h-4 w-4" /> Sign Document</>
            )}
          </Button>
        )}

        {/* OTP entry */}
        {status === "otp_sent" && (
          <>
            <div className="space-y-2">
              <Label htmlFor="esign-otp">Enter eSign OTP</Label>
              <Input
                id="esign-otp"
                placeholder="6-digit OTP"
                value={otp}
                onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))}
                maxLength={6}
                disabled={loading}
                className="font-mono text-center tracking-widest text-lg"
              />
              <p className="text-xs text-muted-foreground">
                OTP sent via Aadhaar-linked mobile for eSign authorization
              </p>
            </div>

            <Button
              onClick={handleSign}
              disabled={otp.length !== 6 || loading}
              className="w-full gap-2"
            >
              {loading ? (
                <><Loader2 className="h-4 w-4 animate-spin" /> Applying Signature...</>
              ) : (
                <><Shield className="h-4 w-4" /> Apply Digital Signature</>
              )}
            </Button>
          </>
        )}

        {/* Error */}
        {error && (
          <div className="flex items-center gap-2 text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-500/10 p-3 rounded-lg">
            <AlertTriangle className="h-4 w-4 flex-shrink-0" />
            {error}
          </div>
        )}

        {/* Failed — retry */}
        {status === "failed" && (
          <Button
            variant="outline"
            onClick={() => { setStatus("pending"); setOtp(""); setError(null); }}
            className="w-full"
          >
            Try Again
          </Button>
        )}

        {/* Legal disclaimer */}
        <p className="text-[10px] text-muted-foreground leading-tight">
          Digital signatures are issued by CCA-licensed Certifying Authorities under
          the Information Technology Act, 2000. Protean eGov Technologies (formerly NSDL)
          acts as the eSign Service Provider (ESP). Signatures are legally equivalent
          to handwritten signatures per Section 3A of the IT Act.
        </p>
      </CardContent>
    </Card>
  );
}
